FROM nginx:stable-perl

ADD ./config/conf.d/default.conf /etc/nginx/conf.d/default.conf
ADD ./config/sites/default.conf /etc/nginx/sites-available/default.conf
ADD ./config/nginx.conf /etc/nginx/nginx.conf
#ADD ./config/.htpasswd /etc/nginx/.htpasswd
EXPOSE 80