apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o .k8s/kubernetes/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    name: varnish
  name: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      name: varnish
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: varnish
    spec:
      containers:
      - image: darkanakin41/kubernetes-playground-varnish:latest
        name: varnish
        resources: {}
      restartPolicy: Always
status: {}
