FROM redis:6.0-alpine

COPY ./{% if docker.compose.service_context_root %}.k8s/docker/redis/{% endif %}config/redis.conf /usr/local/etc/redis/redis.conf

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]